# Generated by Django 3.2.6 on 2021-08-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='movie',
        ),
    ]
