# Generated by Django 3.2.6 on 2021-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
